### ISSUE TITLE
How to get the full path of a file? (Android)

### ISSUE THREAD

**Issue by zipgenius** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#1]
Hello.
How do I get the full path of a file?

**Comment by rafaelrmou** [comment]
With OpenFile we use the same folder local of SaveFile, but i will create a GetPath() and inside SaveFile and PickFile i will return that property too.
Date: Fri, 27 May 2016 08:16:39 -0700

**Comment by hoshisato** [comment]
I would also like to get the path to the file selected

**Comment by nvlled** [comment]
Any update on this?

**Comment by jfversluis** [comment]
@hoshisato & @nvlled since the project seems abandoned I've forked it and added this feature.
You can find it here on [Github](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows). It's also on NuGet :)

**Comment by nvlled** [comment]
@jfversluis Yeah, I ended up creating my own simple file explorer since I just needed the the full path of a file. I considered other options such as temporary files, since but it was horribly inefficient it reads the whole contents of the file in memory.

I'll try the fork when I need a file picker again, thanks.

**Comment by jfversluis** [comment]
I also fixed that in mine. It now streams the files :)

Good to hear you've found and alternative! Cheers!

**Comment by jfversluis** [comment]
Fixed in code now, will release a new version on NuGet soon!
