### ISSUE TITLE
CrossFilePicker.Current.PickFile not work on PCL project

### ISSUE THREAD

**Issue by simon023** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#6]
I tried to use CrossFilePicker PickFile function to choose file in my xamarin form but it doesn't work.

It said "This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

Does it supposed to work .

**Comment by simon023** [comment]
Never mind... It works

**Comment by riandesign** [comment]
@slam023  I got that error when I tried it on iOS.
How did it work for you?

**Comment by jfversluis** [comment]
@riandesign you should install the NuGet package on both the PCL as well as the platform project you are trying to use it on.

**Comment by grammatn** [comment]
I have installed it on all projects. However I am still getting the error message

**Comment by jfversluis** [comment]
That shouldn't happen. Could you try to create a reproduction sample project?

**Comment by grammatn** [comment]
I done it with a sample project and I have the same problem with the following error:

This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

**Comment by Jamarsoft** [comment]
I too have that error.  I have the nuget package installed across both Android and iOS. The package is also installed on the shared project.

When I run the app on Android it opens the file browser with no issue.  When I run it on the ios simulator it gives me 

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Error.

Any assistance would be awesome

Thanks

James

**Comment by caiorios** [comment]
I am facing the same problem on iOS.

**Comment by SatanEnglish** [comment]
Check the references.
It had the references for the pcl in the iOS on instead of MonoTouch10
